server:
  port: 9443
  ssl:
    key-store: classpath:server.p12
    key-store-password: Secr3t
    key-store-type: pkcs12
    key-store-alias: https

spring:
  security:
    oauth2:
      client:
        registration:
          idsvr:
            client-name: Login with the Curity Identity Server
            client-id: www
            client-secret: Secr3t
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid, profile
        provider:
          idsvr:
            issuer-uri: http://localhost:8443/oauth/v2/oauth-anonymous
