apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: curity-services
  name: curity-services
spec:
  ports:
  - name: "6749"
    port: 6749
    protocol: TCP
    targetPort: 6749
  selector:
    tier: curity
  type: NodePort
status:
  loadBalancer: {}
