apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: curity
    tier: curity
  name: curity
spec:
  containers:
  - image: curity/idsvr
    name: curity
    env:
      - name: PASSWORD
        value: curity
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
